In [11]:
import pandas as pd

In [12]:
file = "2020_US_Region_Mobility_Report.csv"

In [13]:
df = pd.read_csv(file)
df.head()

,country_region_code,country_region,sub_region_1,sub_region_2,metro_area,iso_3166_2_code,census_fips_code,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
0,US,United States,NaN,NaN,NaN,NaN,NaN,2/15/2020,6.0,2.0,15.0,3.0,2.0,-1.0
1,US,United States,NaN,NaN,NaN,NaN,NaN,2/16/2020,7.0,1.0,16.0,2.0,0.0,-1.0
2,US,United States,NaN,NaN,NaN,NaN,NaN,2/17/2020,6.0,0.0,28.0,-9.0,-24.0,5.0
3,US,United States,NaN,NaN,NaN,NaN,NaN,2/18/2020,0.0,-1.0,6.0,1.0,0.0,1.0
4,US,United States,NaN,NaN,NaN,NaN,NaN,2/19/2020,2.0,0.0,8.0,1.0,1.0,0.0

In [14]:
mobility_df = df.loc[:,["census_fips_code","retail_and_recreation_percent_change_from_baseline",
                        "grocery_and_pharmacy_percent_change_from_baseline","parks_percent_change_from_baseline",
                        "transit_stations_percent_change_from_baseline","workplaces_percent_change_from_baseline",
                        "residential_percent_change_from_baseline"]]

In [15]:
mobility_df

,census_fips_code,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
0,NaN,6.0,2.0,15.0,3.0,2.0,-1.0
1,NaN,7.0,1.0,16.0,2.0,0.0,-1.0
2,NaN,6.0,0.0,28.0,-9.0,-24.0,5.0
3,NaN,0.0,-1.0,6.0,1.0,0.0,1.0
4,NaN,2.0,0.0,8.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...
581567,56045.0,NaN,NaN,NaN,NaN,-22.0,NaN
581568,56045.0,NaN,NaN,NaN,NaN,-15.0,NaN
581569,56045.0,NaN,NaN,NaN,NaN,-19.0,NaN
581570,56045.0,NaN,NaN,NaN,NaN,-14.0,NaN
581571,56045.0,NaN,NaN,NaN,NaN,-12.0,NaN

In [16]:
df.to_csv('Mobility_1.csv')